# Generated by Django 4.2.4 on 2023-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectimages',
            field=models.ManyToManyField(blank=True, null=True, to='login.projectimage'),
        ),
    ]
